#!/bin/sh
# https://medium.com/@radlinskii/writing-the-pre-commit-git-hook-for-go-files-810f8d5f1c6f

# Handle missing files
# https://gist.github.com/radlinskii/0ba6ec694b1e590d8457c98a358f335f
STAGED_GO_FILES=$(git diff --cached --name-status --diff-filter d -- '*.go' | awk '{ print $2 }')

for FILE in $STAGED_GO_FILES
do
  go fmt $FILE
  git add $FILE
done

exit 0
