version: '3.7'
services:
  mongo:
    # one node mongoDB replica set for local development
    container_name: mongodb
    image: mongo:5
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
    command: ["--replSet", "rs0", "--bind_ip_all"]
  app:
    build:
      context: .
      target: tester
    environment:
      FLOWIFY_DB_CONFIG_ADDRESS: mongo
      FLOWIFY_DB_CONFIG_PORT: 27017
    depends_on:
      - mongo
    volumes:
      - ./testoutputs:/go/src/github.com/equinor/flowify-workflows-server/testoutputs
    command: make UNITTEST_COVERAGE=1 unittest
