FROM golang:1.19-alpine as base
LABEL description="Flowify dev environment"
RUN apk add --no-cache \
    bash \
    binutils \
    curl \
    docker \
    gcc \
    git \
    jq \
    make \
    musl-dev \
    openssl \
    shadow 

FROM base as buildbase
WORKDIR /root
RUN curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.15.0/kind-linux-amd64 && \
    chmod +x ./kind && \
    mv ./kind /usr/local/bin/kind
RUN mkdir -p $GOPATH/src/github.com/equinor/
WORKDIR $GOPATH/src/github.com/equinor/flowify-workflows-server
COPY dev/flowify_server_runner.sh .
RUN chmod +x ./flowify_server_runner.sh
COPY dev/kind_cluster_config_export.sh .
RUN chmod +x ./kind_cluster_config_export.sh
COPY go.mod .
COPY go.sum .
RUN go mod download
ENV PATH="${PATH}:/root"

FROM buildbase as devbase
RUN go install github.com/jstemmer/go-junit-report@latest
RUN go install github.com/jandelgado/gcov2lcov@latest

FROM devbase as devserver
COPY apiserver ./apiserver
COPY auth ./auth
COPY cmd ./cmd
COPY models ./models
COPY pkg ./pkg
COPY rest ./rest
COPY storage ./storage
COPY transpiler ./transpiler
COPY user ./user
COPY config.yml .
COPY main.go .
COPY Makefile .
COPY e2etest ./e2etest


ARG FLOWIFY_GIT_SHA
RUN ["/bin/bash", "-c", "make server strip=1 flowify_git_sha=${FLOWIFY_GIT_SHA}"]

CMD ["./flowify_server_runner.sh"]