version: "3.7"
services: 
  mongo:
    # one node mongoDB replica set for local development
    container_name: mongo_server
    image: mongo:5.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    # volumes:
    #   - ./database-rs:/data/db
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
    command: ["--replSet", "rs0", "--bind_ip_all"]

  cluster:
    container_name: kind_cluster
    build:
      context: ../
      dockerfile: dev/Dockerfile
    image: dev_server
    command: ["cluster_runner.sh"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mongo
    environment:
      - KUBERNETES_SERVICE_HOST=cluster-control-plane
      - KUBERNETES_SERVICE_PORT=6443
      - FLOWIFY_MONGO_ADDRESS=mongo_server
      - FLOWIFY_MONGO_PORT=27017
      - FLOWIFY_K8S_NAMESPACE=argo
      - TENANT_ID=sandbox
      - CLIENT_ID=flowify
      - JWKS_URI=DISABLE_JWT_SIGNATURE_VERIFICATION
    healthcheck:
      test: kubectl rollout status deployments -n argo --timeout=1s || exit 1
      interval: 30s
      retries: 5
      start_period: 20s
      timeout: 120s
  
  server:
    container_name: flowify_sevrver
    image: dev_server
    command: ["flowify_server_runner.sh"]
    ports:
      - "8842:8842"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      cluster:
        condition: service_healthy
    environment:
      - KUBERNETES_SERVICE_HOST=cluster-control-plane
      - KUBERNETES_SERVICE_PORT=6443
      - FLOWIFY_MONGO_ADDRESS=mongo_server
      - FLOWIFY_MONGO_PORT=27017
      - FLOWIFY_K8S_NAMESPACE=argo
      - TENANT_ID=sandbox
      - CLIENT_ID=flowify
      - JWKS_URI=DISABLE_JWT_SIGNATURE_VERIFICATION

networks:
  default:
    name: kind
    external: false
    driver: bridge
