FROM alpine:latest as base
LABEL description="Flowify cluster environment"
RUN apk add --no-cache \
    bash \
    bash-completion \
    curl \
    docker \
    openssl \
    vim

FROM base as buildbase
WORKDIR /root
# Install kubectl
RUN curl -LO https://dl.k8s.io/release/v1.25.0/bin/linux/amd64/kubectl && \
    chmod +x ./kubectl && \
    mv ./kubectl /usr/local/bin/kubectl
# Install Kubernetes in Docker (kind)
RUN curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.15.0/kind-linux-amd64 && \
    chmod +x ./kind && \
    mv ./kind /usr/local/bin/kind
# Install argo
RUN curl -LO https://github.com/argoproj/argo-workflows/releases/download/v3.4.0/argo-linux-amd64.gz && \
    gunzip argo-linux-amd64.gz && \
    chmod +x argo-linux-amd64 && \
    mv ./argo-linux-amd64 /usr/local/bin/argo
RUN echo 'source <(kubectl completion bash)' >>~/.bashrc
RUN echo 'source <(argo completion bash)' >>~/.bashrc
COPY dev/cluster_runner.sh .
COPY dev/kind.yaml .
COPY dev/argo-cluster-install/ ./argo-cluster-install
RUN chmod +x ./cluster_runner.sh

ENTRYPOINT ["/bin/bash", "cluster_runner.sh"]
