version: "3.7"
services: 
  mongo:
    extends:
      file: docker-compose.yaml
      service: mongo

  cluster:
    container_name: flowify_cluster_side_effect
    build:
      context: ../
      dockerfile: dev/Dockerfile-cluster-side-effect
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - KUBERNETES_SERVICE_HOST=cluster-control-plane
      - KUBERNETES_SERVICE_PORT=6443

  flowify-e2e-runner:
    container_name: flowify_e2e-runner
    build:
      context: ../
      # Use the parent folder as context and its Dockerfile
    depends_on:
      - cluster
      - mongo
    environment:
      - KUBERNETES_SERVICE_HOST=cluster-control-plane
      - KUBERNETES_SERVICE_PORT=6443
    command: make e2etests

networks:
  default:
    name: kind
    external: false
    driver: bridge