version: "3.7"
services: 
  mongo:
    # one node mongoDB replica set for local development
    container_name: mongo_server
    image: mongo:5.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    # volumes:
    #   - ./database-rs:/data/db
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
    command: ["--replSet", "rs0", "--bind_ip_all"]

  server:
    container_name: flowify_server
    build:
      context: ../
      dockerfile: dev/Dockerfile-k8s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # args:
        # buildno: 1
    depends_on:
      - mongo
    ports:
      - "8842:8842"
    environment:
      - KUBERNETES_SERVICE_HOST=cluster-control-plane
      - KUBERNETES_SERVICE_PORT=6443
      - FLOWIFY_MONGO_ADDRESS=mongo_server
      - FLOWIFY_MONGO_PORT=27017
      - FLOWIFY_K8S_NAMESPACE=argo

networks:
  default:
    name: kind
    external: false
    driver: bridge
