FROM ghcr.io/equinor/flowify-dev-builder:latest as devserver
COPY go.mod .
COPY go.sum .
RUN go mod download
ENV PATH="${PATH}:/root"

 
COPY apiserver ./apiserver
COPY auth ./auth
COPY cmd ./cmd
COPY models ./models
COPY pkg ./pkg
COPY rest ./rest
COPY storage ./storage
COPY transpiler ./transpiler
COPY user ./user
COPY config.yml .
COPY main.go .
COPY Makefile .
RUN ["/bin/bash", "-c", "make server"]

ENTRYPOINT ["/bin/bash", "flowify_server_runner.sh"]
