version: "3.7"
# This test runner needs to be merged with the docker-compose defining the cluster and mongo services
# Usage: docker-compose -f docker-compose.yaml -f docker-compose-e2e.yaml ... 
services:
  flowify-e2e-runner:
    container_name: flowify_e2e-runner
    build:
      context: ../
      dockerfile: dev/Dockerfile.server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      cluster:
        condition: service_healthy
      mongo:
        condition: service_healthy
    environment:
      - KUBERNETES_SERVICE_HOST=cluster-control-plane
      - KUBERNETES_SERVICE_PORT=6443
      - FLOWIFY_DB_SELECT=mongo
      - FLOWIFY_DB_CONFIG_ADDRESS=mongo_server
      - FLOWIFY_DB_CONFIG_PORT=27017
      - FLOWIFY_SERVER_PORT=8842
      - FLOWIFY_KUBERNETES_NAMESPACE=argo
      - FLOWIFY_KUBERNETES_KUBECONFIGPATH=/root/.kube/config
      - FLOWIFY_AUTH_HANDLER=azure-oauth2-openid-token
      - FLOWIFY_AUTH_CONFIG_KEYSURL=DISABLE_JWT_SIGNATURE_VERIFICATION
    command: bash -c "./kind_cluster_config_export.sh; make e2etest"
