FROM golang:1.19.6-alpine as base
LABEL description="Flowify dev environment builder"
RUN apk add --no-cache \
    bash \
    binutils \
    curl \
    docker \
    gcc \
    git \
    jq \
    make \
    musl-dev \
    openssl \
    shadow 

FROM base as buildbase
WORKDIR /root
RUN curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.15.0/kind-linux-amd64 && \
    chmod +x ./kind && \
    mv ./kind /usr/local/bin/kind
RUN mkdir -p $GOPATH/src/github.com/equinor/
WORKDIR $GOPATH/src/github.com/equinor/flowify-workflows-server
COPY dev/flowify_server_runner.sh .
RUN chmod +x ./flowify_server_runner.sh
