---
apiVersion: v1
kind: ConfigMap
metadata:
    labels:
        app.kubernetes.io/component: "workspace-config"
        app.kubernetes.io/part-of: "flowify"
    name: "sandbox-project-a"
    namespace: "argo"
data:
    roles: "[[\"sandbox-developer\"]]"
---
apiVersion: v1
kind: ConfigMap
metadata:
    labels:
        app.kubernetes.io/component: "workspace-config"
        app.kubernetes.io/part-of: "flowify"
    name: "sandbox-project-b"
    namespace: "argo"
data:
    roles: "[\"sandbox-admin\"]"
---
apiVersion: v1
kind: ConfigMap
metadata:
    labels:
        app.kubernetes.io/part-of: "flowify"
    name: "role-descriptions"
    namespace: "argo"
data:
    "sandbox-developer": "Need to play in the sandbox"
    "sandbox-admin": "Required for God-mode"
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    workflows.argoproj.io/default-artifact-repository: default-v1
  name: artifact-repositories
  namespace: argo
data:
  default-v1: |
    archiveLogs: true
    s3:
      bucket: my-bucket
      endpoint: minio.argo.svc.cluster.local:9000
      insecure: true
      accessKeySecret:
        name: my-minio-cred
        key: accesskey
      secretKeySecret:
        name: my-minio-cred
        key: secretkey
  empty: ""
  my-key: |
    archiveLogs: true
    s3:
      bucket: my-bucket
      endpoint: minio.argo.svc.cluster.local:9000
      insecure: true
      accessKeySecret:
        name: my-minio-cred
        key: accesskey
      secretKeySecret:
        name: my-minio-cred
        key: secretkey
---