apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo
resources:
- namespace.yaml
- configmaps.yaml
- secrets.yaml
- https://github.com/argoproj/argo-workflows/releases/download/v3.4.0/install.yaml
- clusterroles.yaml
- deployments.yaml
- services.yaml