name: Build public docker images to ghcr  
 
on: 
  release:
    types: [published]

permissions:
      id-token: write
      contents: read
      packages: write
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout branch
      uses: actions/checkout@v1

    - name: GitHub Container Registry login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Initialize BuildX
      uses: docker/setup-buildx-action@v1

    - name: Build and push docker image (for k8s deploy)
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ghcr.io/equinor/flowify-workflows-server:${{ github.event.release.tag_name }}
          ghcr.io/equinor/flowify-workflows-server:latest

    - name: Build and push docker image (for local run)
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dev/Dockerfile.server
        push: true
        tags: |
          ghcr.io/equinor/flowify-workflows-server-local:${{ github.event.release.tag_name }}
          ghcr.io/equinor/flowify-workflows-server-local:latest