name: Build public docker images to ghcr  
 
on: 
  workflow_dispatch:
  push:
    paths-ignore:
      - ".github/**"
    tags: '*'
    branches:
      - main
permissions:
      id-token: write
      contents: read
      packages: write
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout branch
      uses: actions/checkout@v1
      with: 
          ref: main

    - name: Set image tag and short sha
      run: |
        echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: GitHub Container Registry login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Initialize BuildX
      uses: docker/setup-buildx-action@v1

    - name: Build and push docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ghcr.io/equinor/flowify-workflows-server:${{ env.SHORT_SHA}} 
          ghcr.io/equinor/flowify-workflows-server:latest
